server:
  port: 8005
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: student1-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sprnew
    username: root
    password: vansh
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true